version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - 8000:8000
    restart: always
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile.web
    ports: 
      - 80:80
    restart: always