version: "3.7"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#
services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - PGUSER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=md5
    env_file:
      - .env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"
  web:
    build: .
    command: python3 -m uvicorn app.main:app --host 0.0.0.0 --reload --log-config=log_conf.yaml
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      
volumes:
  postgres_data: