# Use an official Node.js runtime as a parent image
FROM node:18-alpine as build
WORKDIR /src

COPY ./frontend/web/package*.json .

# Install dependencies
RUN npm install --loglevel verbose
RUN npm install -g @angular/cli@10.1.7
# Copy the rest of the app's source code to the container
COPY ./frontend/web/ /src/

# Build the Angular app
RUN npm run build

FROM nginx:1.25.0-alpine

COPY --from=build /src/dist/web/ /usr/share/nginx/html

RUN npm install typed.js --save

# RUN touch /usr/share/nginx/html/.well_known
# RUN apk update && \
#     apk add --no-cache certbot

# RUN yes | certbot certonly \
#   --webroot -w /usr/share/nginx/html \
#   -d hientran.tech \
#   --email minhhien1772000@gmail.com

# RUN echo "ssl_certificate /etc/letsencrypt/live/hientran.tech/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/hientran.tech/privkey.pem;" > /etc/nginx/snippets/ssl-hientran.tech.conf

EXPOSE 80 443

# CMD ["ng", "serve"]