# Use an official Node.js runtime as a parent image
FROM node:18-alpine as build
WORKDIR /src

COPY ./frontend/web/package*.json .

# Install dependencies
RUN npm install --loglevel verbose
RUN npm install -g @angular/cli
# Copy the rest of the app's source code to the container
COPY ./frontend/web/ /src/

# Build the Angular app
RUN npm run build

FROM nginx:1.25.0-alpine

COPY --from=build /src/dist/web/browser /usr/share/nginx/html

RUN apk update && \
    apk add --no-cache certbot

RUN letsencrypt certonly -a webroot \
  -w /src/dist/web/browser \
  -d hientran.tech -d www.hientran.tech

RUN echo "ssl_certificate /etc/letsencrypt/live/toidicafe.vn/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/toidicafe.vn/privkey.pem;" > /etc/nginx/snippets/ssl-hientran.tech.conf

EXPOSE 80 443

# CMD ["ng", "serve"]