name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Rebuild-up:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rebuild and compose up
      run: docker-compose up --build
  
