name: Front-End CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.web
          push: true
          tags: |
            minhhien1772000/panda-fe:latest

  deploy:
    needs: build-and-push
    name: Deploy Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Connect and pull
        run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && \
            docker ps -aqf 'name=panda-fe' | xargs -r docker stop && \
            docker pull minhhien1772000/panda-fe && \
            docker run --rm -dp 80:80 minhhien1772000/panda-fe:latest"      
      - name: Cleanup
        run: rm -rf ~/.ssh
          
